### PR TITLE
Remove note about windows specific installation of the single exe

### PR DESCRIPTION
**Pull request by develohpanda**
### Summary

What it says on the tin.

This PR is intended for the next release. Does it need to be labelled as such?

### Reason

We resolved Windows archiving issues with https://github.com/Kong/insomnia/pull/4202

### CODE REVIEW

**Comment by falondarville** [comment]
> This PR is intended for the next release. Does it need to be labelled as such?

Let me know if we have a release identifier (name/number) and I can create a label.

**Comment by develohpanda** [comment]
We don't have a version yet; probably just "next"?

**Comment by falondarville** [comment]
> We don't have a version yet; probably just "next"?

Do you have an ETA on the release? Maybe I can use that? "Next" is too vague for me to properly keep track of.

**Review by falondarville — APPROVED** [review]
LGTM

**Comment by falondarville** [comment]
We introduced tabs for Inso CLI Install: https://docs.insomnia.rest/inso-cli/install Should I remove the Windows tab?

**Comment by develohpanda** [comment]
> We introduced tabs for Inso CLI Install: [docs.insomnia.rest/inso-cli/install](https://docs.insomnia.rest/inso-cli/install) Should I remove the Windows tab?

Updated now! I also updated the links to point to 2.4.1.

**Review by falondarville — APPROVED** [review]
LGTM!

**Pull request merged**
